swagger: "2.0"
info:
  version: "1.0.0"
  title: "Use API Spotify"
host: "localhost:3000"
basePath: "/api"
schemes:
- http
tags:
- name: Login/Sign Up
- name: User Manager
- name: User Space
paths:
  "/login":
    post:
      tags:
      - Login/Sign Up
      parameters:
      - name: list
        in: body
        schema:
          $ref: '#/definitions/User'
      summary: "Se connecter"
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/User'
  "/sign_up":
    post:
      tags:
      - Login/Sign Up
      summary: "S'inscrire"
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/UserCreation'
  "/users/{userId}":
    parameters:
    - name: userId
      in: path
      type: string
      required: true

    patch:
      tags:
      - User Manager
      summary: "Update an user"
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/UserUpdate'
        404:
          description: Not Found
          schema:
            $ref: '#/definitions/NotFound'
  "/space ":
    patch:
      tags:
      - User Space
      summary: "Update my user"
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/UserUpdate'
        404:
          description: Not Found
          schema:
            $ref: '#/definitions/NotFound'
    get:
      tags:
      - User Space
      summary: "See my profile"
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/User'
        404:
          description: Not Found
          schema:
            $ref: '#/definitions/NotFound'

definitions:
  User:
    type: object
    properties:
      "_id":
        type: number
      email:
        type: string
        format: email
      password:
        type: string
  UserCreation:
    type: object
    properties:
      "_id":
        type: number
      email:
        type: string
        format: email
      password:
        type: string
  UserUpdate:
    type: object
    properties:
      email:
        type: string
        format: email
      password:
        type: string
  NotFound:
    type: object
    properties:
      message:
        type: string
      status:
        type: number
